### ISSUE TITLE
migration note

### ISSUE THREAD

**Issue by jpca** [spi4j/spi4j#2]
Hello, is there any migration note about Spi4J to upgrade from one version to another ? I'm analysing a code using version 0.15.2. Thanks for the answer

**Comment by spi4j-pacman** [comment]
Bonjour,
il n'existe pas de note indiquant comment migrer de la version 0.15.2 à la dernière version 1.6.
Par contre vous trouverez les releases notes des versions sur googlecode (0.14 à 1.5) puis sur github (1.6).

La version 0.15.2 que vous utilisez correspond à un fork de notre version 0.15 qui date de mars 2012
La prochaine version fonctionnera sur un eclipse Luna (4.4) avec les plugins Sirius (ObeoDesigner community 7.0.1) ainsi que les plugins OD4IS (Entity, DTO/SOA, Cinematic et Requirement)

Lien de téléchargement de ObeoDesigner community 7.0.1 : http://www.obeodesigner.com/component/content/article/430
